[build]
  # Build command for the frontend
  command = "cd client && npm install --legacy-peer-deps --force && NODE_OPTIONS='--openssl-legacy-provider' npm run build"
  
  # Publish directory (where the built files are located)
  publish = "client/build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NODE_OPTIONS = "--openssl-legacy-provider"

# Redirect all API calls to the backend
# ✅ Using your deployed Render backend
[[redirects]]
  from = "/api/*"
  to = "https://typapp-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Redirect all other routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://typapp-backend.onrender.com;"

# Environment variables that will be available in Netlify
# ✅ Using your deployed Render backend
[context.production.environment]
  REACT_APP_API_URL = "https://typapp-backend.onrender.com"
  REACT_APP_GEMINI_API_KEY = "your_gemini_api_key_here"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://typapp-backend.onrender.com"
  REACT_APP_GEMINI_API_KEY = "your_gemini_api_key_here" 