[build]
  # Build command for the frontend
  command = "cd client && npm install --legacy-peer-deps && npm run build"
  
  # Publish directory (where the built files are located)
  publish = "client/build"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirect all API calls to the backend
# Update this URL with your actual backend URL
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

# Redirect all other routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://your-backend-url.com;"

# Environment variables that will be available in Netlify
# These should be set in the Netlify dashboard
[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"
  REACT_APP_GEMINI_API_KEY = "your_gemini_api_key_here"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-url.com"
  REACT_APP_GEMINI_API_KEY = "your_gemini_api_key_here" 